spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Douyin?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: clh13004929816@
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      # 缓存空值，解决缓存穿透问题
      cache-null-values: true
      use-key-prefix: true
      # 设置缓存过期时间
      time-to-live: 3600000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 10010
